### ISSUE TITLE
PostgreSQL multi-threading 

### ISSUE THREAD

**Issue by Amenocy** [tolyo/open-outcry#1]
Hi

thank you for publishing your work, I was working on the same service and surprisingly with the same approach! satisfied to see your project :)
we developed PSQL functions for matching, trading(fund transfers), and deposit/withdraw functionality.
I didn't check the codebase yet, does your architecture allows PostgreSQL to work multi-threaded? or you are using a queue for each trading pair ( or all pairs )? if not how do you guarantee double spending protection and the irreversible nature of the market at the same time?

**Comment by tolyo** [comment]
Hi,
Thank you for comments. All PL/pgSQL functions are executed as a single transaction so you would delegate to connection pool workers to sort out the ordering for you.
