### ISSUE TITLE
Docker compose run connection refused

### ISSUE THREAD

**Issue by vahidsabet** [tolyo/open-outcry#9]
Hi
When running docker compose, I get connection refused from app:

open-outcry-app   "/exchange"              About a minute ago   Exited (1) About a minute ago
time="2023-10-29T12:38:56Z" level=fatal msg="dial tcp 172.24.0.2:5432: connect: connection refused"

any solution?

**Comment by tolyo** [comment]
Can you provide all the commands you are running? Docker version?
```
docker compose run -d db
make setup
make db-update
make test
```

**Comment by tolyo** [comment]
Assuming this is fixed
